In [5]:
import pandas as pd

In [7]:
# Regression

df = pd.read_csv('../data/student_performent_prediction/mat2.csv')

df

df.shape

df.columns

# featuer selection
data = df[['G1', 'G2', 'G3', 'studytime', 'failures', 'absences']]

X = data.drop(columns = 'G3')
y = data['G3']

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model

model.fit(X.values, y.values)
model.predict([[20, 15, 12, 15, 18]])

## Test Accuracy
### Some data for prediction and some for testing

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train.values, y_train.values)
prediction = model.predict(X_test.values)

## errors and accuracy
### exactly milyo ki milena : accuracy

#### jhandai mulyo ki milena : mean sq error, mean absoulte errror, r2 score

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
mse = mean_squared_error(prediction, y_test)
mse

model.coef_

model.intercept_

import numpy as np
X_test = np.array(X_test)
y_test = np.array(y_test)

for i in range(len(prediction)):
    print(X_test[i], y_test[i], prediction[i])

[7 6 2 0 4] 6 5.339687695243286
[7 6 1 1 0] 0 5.135416785444266
[14 15  2  0  4] 15 15.177805985282514
[11 12  2  0 10] 13 11.969068999650908
[10 10  4  0  0] 10 9.212926041745778
[16 18  3  0  2] 18 18.16499454340374
[12 10  2  0  8] 11 10.11673613597714
[10  9  4  0  0] 0 8.238955422117677
[14 16  3  0  0] 16 15.853069088278694
[12 13  2  0  2] 12 12.865880530157465
[15 12  3  0  0] 14 12.110384140250048
[18 19  1  0  6] 19 19.92759694746055
[10  9  2  0  0] 0 8.606013835776215
[11  9  2  0 14] 9 9.162335450569259
[18 18  1  0  8] 18 19.01121548273378
[13 13  4  0  4] 12 12.709608801884015
[13 13  2  0  0] 12 12.961488905739898
[ 9  9  1  0 22] 9 9.269826216036313
[16 17  1  0  4] 18 17.6156714923355
[9 9 2 0 2] 10 8.51040546019378
[ 9  9  2  2 15] 9 8.33949135340113
[6 5 1 0 7] 6 4.4824324843126835
[12 15  1  0  0] 15 14.939761821341612
[10  9  2  0  0] 9 8.606013835776215
[ 9 10  2  0  2] 10 9.484376079821882
[5 5 2 0 4] 6 4.059322014647665
[8 9 2 0 8] 10 8.529975394414
[5 0 1 3 0]