In [2]:
import pandas as pd

In [3]:
# Regression

df = pd.read_csv('../data/student_performent_prediction/mat2.csv')

df

df.shape

df.columns

# featuer selection
data = df[['G1', 'G2', 'G3', 'studytime', 'failures', 'absences']]

X = data.drop(columns = 'G3')
y = data['G3']

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model

model.fit(X.values, y.values)
model.predict([[20, 15, 12, 15, 18]])

## Test Accuracy
### Some data for prediction and some for testing

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train.values, y_train.values)
prediction = model.predict(X_test.values)

## errors and accuracy
### exactly milyo ki milena : accuracy

#### jhandai milyo ki milena : mean sq error, mean absoulte errror, r2 score

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
mse = mean_squared_error(prediction, y_test)
mse

model.coef_

model.intercept_

import numpy as np
X_test = np.array(X_test)
y_test = np.array(y_test)

for i in range(len(prediction)):
    print(X_test[i], y_test[i], prediction[i])

[11 11  2  0  2] 10 10.71190530237116
[ 7 10  2  0  0] 11 9.183213194240432
[ 6  9  1  2 14] 8 7.750034019657759
[8 9 2 0 4] 10 8.466956532921825
[12 12  2  1 12] 13 11.704989555573096
[13 12  1  0 20] 12 12.715350921277802
[ 9  8  2  0 10] 8 7.825726094230406
[ 6  5  1  0 14] 5 4.7815095263798
[14 15  2  0  4] 15 15.074467441793056
[ 7  8  2  3 10] 10 6.140887348420556
[14 14  1  0  4] 14 14.200173420764601
[12 14  1  0  0] 15 13.815178263938003
[12 11  1  1 16] 12 10.980747979799013
[ 9  7  2  1 20] 8 6.733778066928041
[ 9 10  3  0  4] 10 9.458721909736393
[12 10  2  1 18] 10 9.962507298736469
[14 12  4  0  6] 13 11.979179394681692
[6 5 3 1 0] 0 3.554054407249007
[7 9 4 0 0] 0 7.9804598492200665
[15 15  2  0  0] 15 15.041886352324793
[13 15  1  0  0] 15 14.916430082083208
[4 0 1 2 0] 0 -1.8641164115366213
[10 10  2  0 17] 10 10.17335015392986
[9 9 2 0 8] 9 8.734480333962313
[ 6  8  1  3 16] 8 6.357981101846643
[10 11  2  0  2] 12 10.594433946585049
[18 19  1  0  6] 19 19.663987378331